# name: Terraform CI/CD

# on:
#     # WordPress配下の .tf もしくはこのワークフローファイル変更時だけ。
#     pull_request:
#         branches: [main]
#         paths:
#             - "WordPress/**/*.tf"
#             - ".github/workflows/terraform.yaml"

#     push:
#         branches: [main]
#         paths:
#             - "WordPress/**/*.tf"
#             - ".github/workflows/terraform.yaml"
# jobs:
#     terraform-plan:
#         # プルリクエスト時、 plan 実行
#         if: github.event_name == 'pull_request'
#         runs-on: ubuntu-latest

#         defaults:
#             run:
#                 working-directory: WordPress

#         env:
#             AWS_REGION: ap-northeast-1

#         permissions:
#             id-token: write
#             contents: read

#         steps:
#             - uses: actions/checkout@v5
#             - uses: hashicorp/setup-terraform@v3
#               with:
#                   terraform_version: 1.8.5

#             - uses: aws-actions/configure-aws-credentials@v4
#               with:
#                   role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
#                   aws-region: ap-northeast-1

#             - run: terraform init
#             - run: terraform fmt -check -recursive
#             - run: terraform validate
#             - run: terraform plan

#     terraform-apply:
#         # マージされた時、apply 実行
#         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#         runs-on: ubuntu-latest

#         defaults:
#             run:
#                 working-directory: WordPress

#         outputs:
#             instance_id: ${{ steps.tf-ec2.outputs.instance_id }}
#             s3_bucket: ${{ steps.tf-s3.outputs.s3_bucket }}

#         env:
#             AWS_REGION: ap-northeast-1

#         permissions:
#             id-token: write
#             contents: read

#         steps:
#             - uses: actions/checkout@v5
#             - uses: hashicorp/setup-terraform@v3
#               with:
#                   terraform_version: 1.8.5

#             - uses: aws-actions/configure-aws-credentials@v4
#               with:
#                   role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
#                   aws-region: ap-northeast-1

#             - run: terraform init
#             - run: terraform apply -auto-approve

#             - name: Get instance ID
#               id: tf-ec2
#               run: |
#                   echo "instance_id=$(terraform output -raw instance_id)" >> $GITHUB_OUTPUT

#             - name: Get S3 bucket
#               id: tf-s3
#               run: |
#                   echo "s3_bucket=$(terraform output -raw s3_bucket)" >> $GITHUB_OUTPUT

#     ansible-build:
#         needs: terraform-apply
#         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#         runs-on: ubuntu-latest

#         defaults:
#             run:
#                 working-directory: WordPress

#         env:
#             AWS_REGION: ap-northeast-1
#             EC2_INSTANCE_ID: ${{ needs.terraform-apply.outputs.instance_id }}
#             S3_BUCKET: ${{ needs.terraform-apply.outputs.s3_bucket }}

#         permissions:
#             id-token: write
#             contents: read

#         steps:
#             - uses: actions/checkout@v5
#             - uses: aws-actions/configure-aws-credentials@v4
#               with:
#                   role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
#                   aws-region: ap-northeast-1

#             # SSM に最適な ansible インストール
#             - name: Install Ansible
#               run: |
#                   pipx uninstall ansible-core || true
#                   pipx install "ansible-core==2.16.6"

#             # SSM 接続用 API & SDK インストール
#             - name: Install dependencies
#               run: |
#                   pipx inject ansible-core boto3 botocore
#                   ansible-galaxy collection install amazon.aws
#                   ansible-galaxy collection install community.mysql

#             # SSM プラグインインストール
#             - name: Install session manager plugin
#               run: |
#                   curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
#                   sudo dpkg -i session-manager-plugin.deb

#             # 動的インベントリ取得
#             - name: Create inventory
#               run: |
#                   echo "[web]" > inventory
#                   echo "$EC2_INSTANCE_ID ansible_connection=amazon.aws.aws_ssm ansible_aws_ssm_region=ap-northeast-1 ansible_aws_ssm_bucket_name=$S3_BUCKET" >> inventory

#             - name: Debug inventory
#               run: cat inventory

#             - name: Run Ansible
#               env:
#                   AWS_REGION: ap-northeast-1
#               run: |
#                   ansible-playbook -i inventory ansible/playbook.yaml -vvv
